sonar.projectKey=GodWindows_devops-tp
sonar.organization=godwindows
sonar.projectName=devops-tp
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py,tests/**/*.js
sonar.exclusions=**/__pycache__/**,**/*.pyc,node_modules/**,coverage/**,.venv/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
