sonar.projectKey=GodWindows_devops-tp
sonar.organization=godwindows
sonar.projectName=devops-tp
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.python.coverage.reportPaths=coverage.xml
